name: CI [ts-helm-charts] Lint-Test

on:
  workflow_call:
  
jobs:
  lint-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    outputs:
      chart: ${{ steps.get-chart.outputs.chart }}
      result: ${{ steps.get-chart.outputs.result }}    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Setup Chart Linting
      id: lint
      uses: helm/chart-testing-action@v2.3.1
      with:
        version: v3.7.1

    - name: List changed charts
      id: list-changed
      run: |
          changed=$(ct --config ./.github/configs/ct.yaml list-changed)
          charts=$(echo "$changed" | tr '\n' ' ' | xargs)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
            echo "::set-output name=changed_charts::$charts"
          fi

    - name: Run chart-testing (lint)
      run: ct lint --debug --config ./.github/configs/ct.yaml --lint-conf ./.github/configs/lintconf.yaml

    - name: Create kind cluster
      if: steps.list-changed.outputs.changed == 'true'
      uses: helm/kind-action@v1.2.0
      with:
        version: v0.12.0
        node_image: kindest/node:v1.23.5

    - name: Run chart-testing (install)
      if: steps.list-changed.outputs.changed == 'true'    
      run: ct install --config .github/configs/ct.yaml
      
    - name: Run chart-testing (upgrade)
      if: steps.list-changed.outputs.changed == 'true'    
      run: ct install --upgrade --config .github/configs/ct.yaml
